name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Getcode
        uses: actions/checkout@v6
      - name: download node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
  Deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Get Code
          run: |
            node -v        